name: databricks-cicd-adventureworks

on:
  push:
    branches:
      - main        # merge a main → actualiza DEV y luego PROD
  workflow_dispatch: # permite ejecución manual

permissions:
  contents: read

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
      REPO_PATH: /Workspace/Users/yd.montenegro.martinez@gmail.com/DEV-DATABRIKS-GIT-FOLDER

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks version

      - name: Update Databricks Repo (DEV) to main
        run: |
          databricks repos update "$REPO_PATH" --branch "main"

  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_PROD }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_PROD }}
      REPO_PATH: /Workspace/Users/yd.montenegro.martinez@gmail.com/PROD-DATABRIKS-GIT-FOLDER

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks version

      - name: Update Databricks Repo (PROD) to main
        run: |
          databricks repos update "$REPO_PATH" --branch "main"
